### ISSUE TITLE
In Sem2/OOPJ/Lab 3 Practical 3 is incomplete.

### ISSUE THREAD

**Issue by SavanSutariya** [SavanSutariya/DDU#4]

**Comment by rahuljogadiya** [comment]
#[Operator.txt](https://github.com/SavanSutariya/DDU/files/10685358/Operator.txt)
#[Shape.txt](https://github.com/SavanSutariya/DDU/files/10685363/Shape.txt)

**Comment by SavanSutariya** [comment]
will you be able to make a pull request
\
